[sqlagent]
enabled = false

[EULA]
accepteula = Y

[coredump]
captureminiandfull = true
coredumptype = mini

[filelocation]
defaultbackupdir = /var/opt/mssql/data
defaultdatadir = /var/opt/mssql/data
defaultlogdir = /var/opt/mssql/log
defaultdumpdir = /var/opt/mssql/log

[memory]
memorylimitmb = 3072

[network]
tcpport = 1433
ipaddress = 0.0.0.0

[language]
lcid = 3082
